image: node:9

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

unit_tests:
  stage: test
  script:
    - npm run lint
    - npm run test:unit
  tags:
    - node

deploy_staging:
  stage: deploy
  variables:
    NODE_ENV: staging
  script:
    - npm run dist
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - \curl -sSL https://get.rvm.io | bash -s stable --ruby
    - gem install dpl
    - dpl --provider=heroku --app=cracra-staging --api-key=$HEROKU_STAGING_API_KEY --skip_cleanup=true
    - ls -l
  only:
    - master
  except:
    - tags
  environment:
    name: staging
    url: https://cracra-staging.herokuapp.com
  tags:
    - node

deploy_prod:
  stage: deploy
  variables:
    NODE_ENV: production
  script:
    - npm run dist
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - \curl -sSL https://get.rvm.io | bash -s stable --ruby
    - gem install dpl
    - dpl --provider=heroku --app=cracra --api-key=$HEROKU_STAGING_API_KEY --skip_cleanup=true
    - ls -l
  only:
    - tags
  when: manual
  environment:
    name: production
    url: https://cracra.herokuapp.com
  tags:
    - node
