image: node:9

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build_staging:
  stage: build
  variables:
    NODE_ENV: staging
  script:
    - yarn
    - yarn dist
  artifacts:
    name: "build-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - master
  except:
    - tags
  tags:
    - node

build_production:
  stage: build
  variables:
    NODE_ENV: production
  script:
    - yarn
    - yarn dist
  artifacts:
    name: "build-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - tags
  tags:
    - node

unit_tests:
  stage: test
  script:
    - yarn
    - yarn lint
    - yarn test:unit
  tags:
    - node

deploy_staging:
  image: tmaier/dpl:latest
  stage: deploy
  script:
    - dpl --provider=heroku --app=cracra-staging --api-key=$HEROKU_STAGING_API_KEY --skip_cleanup=true
  only:
    - master
  except:
    - tags
  environment:
    name: staging
    url: https://cracra-staging.herokuapp.com
  dependencies:
    - build_staging
  tags:
    - node

deploy_prod:
  image: tmaier/dpl:latest
  stage: deploy
  script:
    - dpl --provider=heroku --app=cracra --api-key=$HEROKU_STAGING_API_KEY --skip_cleanup=true
  only:
    - tags
  when: manual
  environment:
    name: production
    url: https://cracra.herokuapp.com
  dependencies:
    - build_production
  tags:
    - node
