language: node_js
node_js:
- '6.9'
script:
- npm run test
- npm run dist
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: RV75B50LoQayNBChjPYhzMJgFInbndOxHqgMY+qK5BSp4Am9HvMgL4Wj3PI6+SQqytYqgmg3uAt/OfGCMLcdkAulHG+fsussBTCpzGhxn7TXUHxD3R7PZTA5620Q3AeiupqbDKxy1Eqvmra52N7IEGXLH0dO5HQneewE98ZxwBJPyQ2vFFofCOhCC9okb2qxgOIiz/AbR7dBlxEJZNMgw480Ig/3Cu4nD/LwLeXisfP0/O1PZVyxgftYQessTcFGVfGk/GBo7r2GUhZsWbXrF3WzEY66uBzrfP2JNmb6xUHXFS+BUipvuC9ZUpDRLc86/vkk/WMvDBO2uF30rAzB8eBSqr2hq12wO0r0MEZgxjK0OubiopHgWKOBiiQMgTnK3Tlb3GqDBES2CGny0jX2k9tNSNaN7Yzk7yyvv6JDnU3ZEbyiV6FOZjtaCzlWohM7iG6sIyRaCDZUOx7Hkf/9zOUnrtEdonbysgQ99+TpUUnj+J6nXBIiLfbvDb6fteQmGHHHhxKvenqnBje0mE9C6Py1KOyZswgiYtP3XE6+RqgMY71asicUck020iX6YS8S9CxS5OqfbJAOxj/GuUgTUp+xW+HJefkBEsAhgLx0CJE2S53oOIbltLyC0HlbYcgvKzC/97TiRqwUtlBrZwIimyeBI6Zjh2um65eDtIpa2Ko=
