version: '3'
services:
  web:
    image: node:latest
    container_name: "web"
    working_dir: /usr/src/app
    command: sh -c 'npm install && npm run start:server'
    environment:
      - APP_ENV=dev
    volumes:
      - .:/usr/src/app:rw
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8001:8001
    links:
      - db
    networks:
      - default
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - default
volumes:
  node_modules:
networks:
  default:
    driver: bridge
