build_common: &build_common
  executor:
    name: node/node
    tag: '10'
  working_directory: ~/mylv
  environment:
    NODE_ENV: production
  steps:
  - attach_workspace:
      at: ~/
  - run: yarn build
  - store_artifacts:
      path: ~/mylv/dist
  - store_artifacts:
      path: ~/mylv/packages/emails/dist
  - store_artifacts:
      path: ~/mylv/packages/documents/dist
  - persist_to_workspace:
      root: ~/
      paths:
      - mylv

deploy_common: &deploy_common
  docker:
  - image: buildpack-deps:trusty
  working_directory: ~/mylv
  steps:
  - attach_workspace:
      at: ~/
  - run: git checkout -b release
  - run: git add -f dist/ packages/emails/dist/ packages/documents/dist/
  - run: git config user.email "deploy@circleci.com"
  - run: git config user.name "CircleCI Deployer"
  - run: git commit -m "CircleCI deploy"
  - deploy:
      command: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git release:master

tag_filters: &tag_filters
  tags:
    only: /^v\d+\.\d+\.\d+/

version: 2.1

orbs:
  node: circleci/node@0.0.2

jobs:
  install:
    executor:
      name: node/node
      tag: '10'
    working_directory: ~/mylv
    steps:
    - checkout
    - node/with-cache:
        steps:
          - run: yarn install --frozen-lockfile
        cache-key: yarn.lock
    - persist_to_workspace:
        root: ~/
        paths:
          - mylv
          - .cache/Cypress

  build_dev:
    <<: *build_common
    environment:
      BABEL_ENV: dev

  build_staging:
    <<: *build_common
    environment:
      BABEL_ENV: staging

  build_production:
    <<: *build_common
    environment:
      BABEL_ENV: production

  test:
    executor:
      name: node/node
      tag: '10'
    working_directory: ~/mylv
    steps:
    - attach_workspace:
        at: ~/
    - run: yarn lint
    - run: yarn test -w 8

#  test_e2e:
#    docker:
#    - image: cypress/base:10
#    - image: mongo:4.0
#    working_directory: ~/mylv
#    environment:
#      APP_ENV: test
#    steps:
#    - attach_workspace:
#        at: ~/
#    - run:
#        command: yarn start
#        background: true
#    - run:
#        command: yarn e2e:record
#        no_output_timeout: 1m

  hold_deployment:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - run: echo "Waiting for approval before deployement"

  deploy_staging:
    <<: *deploy_common
    environment:
      HEROKU_APP: mylv-staging

  deploy_production:
    <<: *deploy_common
    environment:
      HEROKU_APP: mylv

workflows:
  version: 2
  general_workflow:
    jobs:
    - install:
        filters:
          branches:
            ignore: master
          tags:
            ignore: /.*/
    - build_dev:
        requires:
          - install
    - test:
        requires:
        - build_dev
#    - test_e2e:
#        requires:
#        - build_dev

  master_workflow:
    jobs:
    - install:
        filters:
          branches:
            only: master
          tags:
            ignore: /.*/
    - build_staging:
        requires:
          - install
    - test:
        requires:
        - build_staging
#    - test_e2e:
#        requires:
#        - build_staging
    - deploy_staging:
        requires:
        - test
#        - test_e2e

  release_workflow:
    jobs:
    - install:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v\d+\.\d+\.\d+/
    - build_production:
        requires:
          - install
        filters: *tag_filters
    - hold_deployment:
        type: approval
        requires:
        - build_production
        filters: *tag_filters
    - deploy_production:
        requires:
        - hold_deployment
        filters: *tag_filters
